language: julia

codecov: true

julia:
    - 1.6

addons:
  apt:
    packages:
    - libhdf5-serial-dev

script:
    - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("PoreMatMod")'

after_success:
    - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("Coverage")'
    - julia --project -e 'using Coverage; Codecov.submit(process_folder())'
    - julia --project ./docs/make.jl

notifications:
  email: true
