site_name:        ""
repo_url:         https://github.com/SimonEnsemble/MOFfun.jl
site_description: Documentation for the julia package MOFun.jl
site_author:      eahenle

theme: windmill

extra_css:
  - assets/flux.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
  - mathjax-config.js

markdown_extensions:
  - pymdownx.arithmatex
  - extra
  - tables
  - fenced_code
  - toc:
      permalink: '#'
  #- toc:
  #    baselevel: 1
  #- mdx_math
extra:
  logo: assets/PMlogo.png


docs_dir: 'build'

pages:
  - MOfun: index.md
  - Getting Started: manual/start.md
  - Loading Data: manual/inputs.md
  - Substructure Search: manual/find.md
  - Sustructure Find/Replace: manual/replace.md
  - Docstrings: manual/docstrings.md
  - MOFunGO: manual/mofungo.md
