name: lapack_blas_versions
on:
  workflow_dispatch:

jobs:
  get-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.6.3"

      - name: Display Versions
        run: julia -e 'using LinearAlgebra; @info "BLAS" LinearAlgebra.BLAS.libblas LinearAlgebra.BLAS.openblas_get_config(); @info "LAPACK" LinearAlgebra.LAPACK.liblapack LinearAlgebra.LAPACK.version()'
